/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LayoutRouteImport } from "./routes/_layout"
import { Route as AuthLayoutRouteImport } from "./routes/_auth-layout"
import { Route as LayoutIndexRouteImport } from "./routes/_layout/index"
import { Route as AuthLayoutLoginRouteImport } from "./routes/_auth-layout/login"
import { Route as AuthLayoutForgotPasswordRouteImport } from "./routes/_auth-layout/forgot-password"

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: "/_auth-layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutForgotPasswordRoute =
  AuthLayoutForgotPasswordRouteImport.update({
    id: "/forgot-password",
    path: "/forgot-password",
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "": typeof LayoutRouteWithChildren
  "/forgot-password": typeof AuthLayoutForgotPasswordRoute
  "/login": typeof AuthLayoutLoginRoute
  "/": typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  "": typeof AuthLayoutRouteWithChildren
  "/forgot-password": typeof AuthLayoutForgotPasswordRoute
  "/login": typeof AuthLayoutLoginRoute
  "/": typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth-layout": typeof AuthLayoutRouteWithChildren
  "/_layout": typeof LayoutRouteWithChildren
  "/_auth-layout/forgot-password": typeof AuthLayoutForgotPasswordRoute
  "/_auth-layout/login": typeof AuthLayoutLoginRoute
  "/_layout/": typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "" | "/forgot-password" | "/login" | "/"
  fileRoutesByTo: FileRoutesByTo
  to: "" | "/forgot-password" | "/login" | "/"
  id:
    | "__root__"
    | "/_auth-layout"
    | "/_layout"
    | "/_auth-layout/forgot-password"
    | "/_auth-layout/login"
    | "/_layout/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth-layout": {
      id: "/_auth-layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_auth-layout/login": {
      id: "/_auth-layout/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    "/_auth-layout/forgot-password": {
      id: "/_auth-layout/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof AuthLayoutForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutForgotPasswordRoute: typeof AuthLayoutForgotPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutForgotPasswordRoute: AuthLayoutForgotPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
